# Generated by Django 2.0.7 on 2018-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahnata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_logo',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
