# Generated by Django 2.0.6 on 2018-08-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahnata', '0002_auto_20180817_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
