# Generated by Django 2.1.1 on 2018-09-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahnata', '0003_auto_20180818_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='articles',
            index_together=set(),
        ),
    ]
